upload_demo/routes.py
from flask import Blueprint, jsonify, render_template, request
import typing as t
from utils import util
from flask import current_app as app

SUCCESS_MESSENGER = "sucsess"
FAIL_MESSENGER = "fail"
bp_upload = Blueprint("upload", __name__, template_folder="templates")

def handle_before_response(data, **context: t.Any):
    SUPPORT_FRONT_END = app.config["SUPPORT_FRONT_END"]
    if SUPPORT_FRONT_END and 'view' in data:
        return render_template(data['view'], **context)
    else:
        if 'view' in data:
            del data["view"]
        return jsonify(data)

@bp_upload.route("/", methods=["GET"])
def upload_demo():
    response = {
        "status": SUCCESS_MESSENGER,
        "message": "Upload a file",
        "view": "upload.html"
    }
    return handle_before_response(response)

@bp_upload.route("/file", methods=["POST"])
def upload_file():
    status = SUCCESS_MESSENGER
    messenge = "Upload success"
    if 'file' not in request.files:
        return "No file part""HOME"

    file = request.files['file']

    if file.filename == '':
        return "No selected file"
    # Check if the file upload was successful
    if not util.upload_file(file):
        messenge = "upload to local fail"
        status = FAIL_MESSENGER
    elif "state" in request.form and request.form["state"] == "upload_to_drive":
        if not util.upload_to_google_drive(file):
            messenge = "upload to google drive fail"
            status = FAIL_MESSENGER
    response = {
        "status": status,
        "message": messenge,
        "view": "home.html"
    }
    return handle_before_response(response,text=messenge)

@bp_upload.route("/upload_to_drive", methods =["GET"])
def upload_to_drive():
    response = {
        "status": SUCCESS_MESSENGER,
        "message": "Upload a file",
        "view": "upload.html"
    }
    return handle_before_response(response, state="upload_to_drive")

upload_demo/templates/upload.html
{% extends "base.html" %}
{% block title %}HOME{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
<script src="https://unpkg.com/three@0.138.3/examples/js/controls/OrbitControls.js"></script>
{% endblock %}
{% block header%}
{% include "header.html" %}
{% endblock %}
{% block main_id %}main_upload{% endblock %}
{% block body %}
<div class="upload-container">
    <h2>Upload demo</h2>
    <form class="upload-form" action="{{url_for('upload.upload_file')}}" method="post" enctype="multipart/form-data">
        {% if state == "upload_to_drive" %}
            <p>Upload to Google Drive</p>
            <input type="hidden" name="state" value="{{state}}">
        {% endif %}
        <label>Select file:</label>
        <input type="file" class="form-control-file" id="file-input" id="file" name="file" required/>
        <button type="submit">Upload</button>
    </form>
</div>
<script src="{{ url_for('static', filename='login.js') }}"></script>
{% endblock %}
{% block footer%}
{% include "footer.html" %}
{% endblock %}